import os
import json
import base64
from flask import Flask, request, jsonify, send_from_directory, Response, stream_with_context
import anthropic
from background_docs import FCV_GUIDE
import io
try:
    from pypdf import PdfReader
except ImportError:
    PdfReader = None

# ── Constants ────────────────────────────────────────────────────────────────

MAX_DOC_CHARS = 140_000
ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD", "fcv-admin-2024")
PROMPTS_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'prompts.json')

DO_NO_HARM_HEADER = """---
**AI-Generated Output — For Review Purposes Only**

This Recommendations Note was produced by an LLM-assisted screening tool. It is intended as a supplementary analytical input to support expert review, not as a substitute for professional FCV analysis. The content reflects the AI interpretation of uploaded documents and embedded WBG guidance, and may contain errors, omissions, or misjudgements. Users are responsible for critically reviewing, verifying, and adapting this output before any operational use.

*Generated by WBG FCV Sensitivity Project Screener · {date}*

---

"""

# ── Default prompts ──────────────────────────────────────────────────────────

DEFAULT_PROMPTS = {
"1": """# Role
You are an expert FCV (Fragility, Conflict, and Violence) analyst for the World Bank Group.

# Task
Analyze the provided project document(s) alongside your knowledge of the country and regional FCV context. Your output must clearly distinguish between two sources of information:
1. What the project document itself flags or implies about FCV risks
2. Wider FCV conditions from your knowledge of reputable sources (UN, ICG, World Bank, ACLED, etc.)

# Output Structure — use exactly these section headings

## Part A: FCV Risks and Indicators from the Project Document
Extract everything FCV-relevant from the uploaded documents under these sub-headings:

### Direct FCV References
Explicit mentions of fragility, conflict, violence, security concerns, displacement, IDPs, refugees, organized crime, or post-conflict context.

### Implicit FCV Indicators
Contextual signals that suggest FCV relevance: weak institutions, social exclusion, intercommunal tensions, resource competition, land disputes, political instability, high youth unemployment.

### Project Design Elements with FCV Implications
Features that interact with FCV dynamics: beneficiary targeting, community engagement, infrastructure siting, employment components, grievance mechanisms.

### Existing Risk Assessments in the Document
Any risk analysis already present: E&S risks, political economy considerations, implementation risks.

### Data Gaps in the Document
FCV-relevant information that appears absent or inadequately addressed in the project document.

---

## Part B: Wider FCV Context from General Knowledge
Draw on your training knowledge of reputable sources — UN Security Council reports, ICG reports, World Bank FCV assessments, ACLED data, Fragile States Index, and other authoritative references. Provide a substantive assessment of:

### Country and Regional FCV Landscape
The broader fragility, conflict, and violence dynamics affecting this country and region. Cite the types of sources you are drawing on (e.g. "According to ICG reporting..." or "World Bank FCV classification indicates..."). Be clear this reflects your training knowledge, not live data.

### Key FCV Risks Relevant to this Sector and Project Type
Risks that commonly affect projects of this type in this context, based on wider evidence — even if not mentioned in the document.

### Alignment or Gaps Between Document and Wider Context
Where does the project document's own risk picture align with or diverge from the wider FCV landscape? What is missing from the document's framing?

---

# Quality Guidelines
- Be precise and evidence-grounded in Part A — quote or paraphrase the document directly
- Be substantive in Part B — draw on specific knowledge of this country, not generic statements
- Always clearly signal which section you are in
- Do not speculate about project specifics beyond what the documents contain
""",

"2": """# Role
You are an FCV specialist conducting systematic screening for World Bank projects.

# Task
Using Stage 1 findings and any user clarifications, analyze this project across six FCV dimensions. Assess both **risks TO the project** and **risks FROM the project**.

For each dimension provide:
1. **Risk Assessment:** High / Medium / Low / Not Applicable (with rationale)
2. **Risk TO Project:** How the FCV context threatens project delivery
3. **Risk FROM Project:** How the project could worsen FCV dynamics

## Dimension 1: Institutional Legitimacy and Capacity
## Dimension 2: Inclusion and Non-Discrimination
## Dimension 3: Social Cohesion and Reconciliation
## Dimension 4: Security and Rule of Law
## Dimension 5: Economic Opportunities and Livelihoods
## Dimension 6: Resilience to Shocks and Crises

End with a **Summary Risk Matrix** table: Dimension / Risk TO Project / Risk FROM Project / Overall Priority (H/M/L/NA).

Quality: evidence-based, balanced, honest about gaps.
""",

"3": """# Role
You are an FCV risk mitigation specialist reviewing project design adequacy.

# Task
Based on Stage 2 analysis and user clarifications, identify:

1. **Critical Gaps** — Analytical, Design, and Implementation gaps
2. **Mitigation Measures** for each HIGH-risk dimension: Risk / Measure / Responsible Actor / Timeline / Resource Implications
3. **Do No Harm Checklist** — assess: Non-discrimination in targeting, Conflict-sensitive site selection, Inclusive consultation, Grievance redress, Conflict impact monitoring, Adaptive management
4. **Enhancement Opportunities** — active peacebuilding beyond do-no-harm
5. **Priority Mitigation Actions** (Top 5) and **Overall FCV Integration Rating** (Strong / Adequate / Weak / Absent)

Quality: specific and actionable, proportionate to risk severity, sector-specific.
""",

"4": """# Role and Context
You are a senior FCV specialist providing collegial technical input to a World Bank Task Team Leader (TTL). Tone: supportive, consultative, operationally focused — a trusted peer reviewer, not an auditor.

# Structure

## 1. MAIN NOTE (~2,000-2,500 words)

**A. Overview** (80-100 words): Project name, country, sector, stage. FCV context in 2-3 sentences. Purpose of this note in one sentence.

**B. Strengths and Gaps** (180-250 words total):
- Strengths paragraph (80-120 words): 3-4 concrete strengths in prose
- Gap paragraph (100-130 words): Main weakness, constructively framed

**C. Operational Context** (150-200 words): 3-4 converging FCV risks. Forward-looking framing.

**D. Strategic Priorities** (4-5 priorities, 120-150 words each): gap / why it matters / suggested approach / optional illustrative text.
Language: "Consider...", "The team may want to...", "Would benefit from..."
NO numbered sub-recommendations. NO specific percentages or dollar amounts.

## 2. TECHNICAL ANNEX (1,200-1,500 words)
3-4 thematic pillars. For each pillar (300-400 words), 2-3 risks:

**Risk [X]: [Title]** (30-45 words)
Options to Consider:
[ ] Option 1 (35-50 words)
[ ] Option 2 (35-50 words)

# Rules
- Citation format: [Document Name Year] — NEVER cite the PCN/PAD being reviewed
- Total: 3,500-3,800 words maximum
- All content specific to THIS project — no generic template language

Now produce the FCV Support Note."""
}


def load_prompts():
    try:
        if os.path.exists(PROMPTS_FILE):
            with open(PROMPTS_FILE, 'r') as f:
                overrides = json.load(f)
            if overrides:
                merged = dict(DEFAULT_PROMPTS)
                merged.update(overrides)
                return merged
    except Exception:
        pass
    return dict(DEFAULT_PROMPTS)


def save_prompts(prompts_dict):
    with open(PROMPTS_FILE, 'w') as f:
        json.dump(prompts_dict, f, indent=2)


def get_prompt_for_stage(stage):
    return load_prompts().get(str(stage))


def get_stage_name(stage):
    return {1: "Identifying FCV Risks", 2: "FCV-Sensitivity Screening",
            3: "Identifying Project Gaps", 4: "Recommendations Note"}.get(stage, f"Stage {stage}")


# ── PDF helper ───────────────────────────────────────────────────────────────

def extract_pdf_text(b64_data, name):
    try:
        pdf_bytes = base64.standard_b64decode(b64_data)
        reader = PdfReader(io.BytesIO(pdf_bytes))
        pages_text = []
        for page in reader.pages:
            try:
                pages_text.append(page.extract_text() or '')
            except Exception:
                pages_text.append('')
        full_text = '\n\n'.join(pages_text)
        page_count = len(reader.pages)
        if len(full_text) > MAX_DOC_CHARS:
            full_text = full_text[:MAX_DOC_CHARS] + (
                f'\n\n[Document truncated at {MAX_DOC_CHARS//1000}k chars of {page_count} pages.]'
            )
        return full_text, page_count
    except Exception as e:
        return f'[Could not extract text from {name}: {str(e)}]', 0


# ── Flask app ────────────────────────────────────────────────────────────────

app = Flask(__name__, static_folder='static')
app.config['MAX_CONTENT_LENGTH'] = 50 * 1024 * 1024
client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))


@app.route('/')
def index():
    base = os.path.dirname(os.path.abspath(__file__))
    static_path = os.path.join(base, 'static')
    if os.path.exists(os.path.join(static_path, 'index.html')):
        return send_from_directory(static_path, 'index.html')
    return send_from_directory(base, 'index.html')


@app.route('/health')
def health():
    return jsonify({'status': 'ok'})


# ── Admin routes ─────────────────────────────────────────────────────────────

@app.route('/admin')
def admin():
    base = os.path.dirname(os.path.abspath(__file__))
    return send_from_directory(os.path.join(base, 'static'), 'admin.html')


@app.route('/api/admin/prompts', methods=['GET'])
def get_prompts():
    if request.headers.get('X-Admin-Password') != ADMIN_PASSWORD:
        return jsonify({'error': 'Unauthorized'}), 401
    return jsonify(load_prompts())


@app.route('/api/admin/prompts', methods=['POST'])
def set_prompts():
    if request.headers.get('X-Admin-Password') != ADMIN_PASSWORD:
        return jsonify({'error': 'Unauthorized'}), 401
    data = request.get_json()
    if not data:
        return jsonify({'error': 'Invalid JSON'}), 400
    save_prompts(data)
    return jsonify({'ok': True})


@app.route('/api/admin/prompts/reset', methods=['POST'])
def reset_prompts():
    if request.headers.get('X-Admin-Password') != ADMIN_PASSWORD:
        return jsonify({'error': 'Unauthorized'}), 401
    save_prompts({})
    return jsonify({'ok': True})


# ── Main analysis route ───────────────────────────────────────────────────────

@app.route('/api/run-stage', methods=['POST'])
def run_stage():
    try:
        data = request.get_json()
        if not data:
            return jsonify({'error': 'Invalid request.'}), 400

        stage = int(data.get('stage', 1))
        conversation_history = data.get('history', [])
        user_message = data.get('user_message', '').strip()

        MAX_ASSISTANT_CHARS = 6000

        prior_outputs = []
        for m in conversation_history:
            if m['role'] == 'assistant':
                c = m['content'] if isinstance(m['content'], str) else ''
                if len(c) > MAX_ASSISTANT_CHARS:
                    c = c[:MAX_ASSISTANT_CHARS] + '\n...[truncated]'
                prior_outputs.append(c)

        if prior_outputs:
            context = "\n\n---\n\n".join(
                f"Stage {i+1} output:\n{o}" for i, o in enumerate(prior_outputs)
            )
            messages = [
                {"role": "user", "content": f"Prior FCV analysis context:\n\n{context}\n\nUse this as the basis for the next stage."},
                {"role": "assistant", "content": "Understood. I will build on this prior analysis."}
            ]
        else:
            messages = []

        if stage == 1:
            documents = data.get('documents', [])
            if not documents:
                return jsonify({'error': 'Please upload at least one project document.'}), 400

            content_parts = []
            project_docs = [d for d in documents if not d.get('isContext')]
            context_docs = [d for d in documents if d.get('isContext')]

            def add_doc(doc, label):
                name = doc.get('name', 'document')
                file_type = doc.get('type', 'text')
                doc_content = doc.get('content', '')
                if file_type == 'pdf':
                    extracted, page_count = extract_pdf_text(doc_content, name)
                    content_parts.append({"type": "text", "text": f"=== {label}: {name} ({page_count} pages) ===\n\n{extracted}"})
                else:
                    text = doc_content[:MAX_DOC_CHARS] + ('\n\n[Truncated]' if len(doc_content) > MAX_DOC_CHARS else '')
                    content_parts.append({"type": "text", "text": f"=== {label}: {name} ===\n\n{text}"})

            for doc in project_docs:
                add_doc(doc, 'PROJECT DOCUMENT')
            if context_docs:
                content_parts.append({"type": "text", "text": "\n\n--- CONTEXTUAL DOCUMENTS ---\n"})
                for doc in context_docs:
                    add_doc(doc, 'CONTEXT DOCUMENT')

            content_parts.append({"type": "text", "text": (
                "\n\n--- WBG FCV Sensitivity and Responsiveness Guide (always included) ---\n" + FCV_GUIDE
            )})
            content_parts.append({"type": "text", "text": get_prompt_for_stage(1)})
            messages.append({"role": "user", "content": content_parts})

        elif user_message:
            messages.append({"role": "user", "content": user_message})
        else:
            messages.append({"role": "user", "content": get_prompt_for_stage(stage)})

        def generate():
            collected = []
            try:
                yield f"data: {json.dumps({'ping': True})}\n\n"

                with client.messages.stream(
                    model="claude-haiku-4-5-20251001",
                    max_tokens=8192,
                    messages=messages
                ) as stream:
                    for text_chunk in stream.text_stream:
                        collected.append(text_chunk)
                        yield f"data: {json.dumps({'chunk': text_chunk})}\n\n"

                full_text = ''.join(collected)

                # Prepend do-no-harm disclaimer to Stage 4
                if stage == 4:
                    from datetime import date
                    header = DO_NO_HARM_HEADER.format(date=date.today().strftime('%d %B %Y'))
                    full_text = header + full_text

                updated_messages = messages + [{"role": "assistant", "content": full_text}]
                if len(updated_messages) > 20:
                    updated_messages = updated_messages[-20:]

                yield f"data: {json.dumps({'done': True, 'result': full_text, 'history': updated_messages, 'stage': stage})}\n\n"

            except anthropic.AuthenticationError:
                yield f"data: {json.dumps({'error': 'Invalid API key.'})}\n\n"
            except Exception as e:
                yield f"data: {json.dumps({'error': str(e)})}\n\n"

        return Response(stream_with_context(generate()), mimetype='text/event-stream',
                        headers={'Cache-Control': 'no-cache', 'X-Accel-Buffering': 'no'})

    except Exception as e:
        return jsonify({'error': str(e)}), 500


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=False, threaded=True)
