"""Small native Word presentation helper for FCV exports.

The helper changes only Word presentation properties and safe display punctuation.
It keeps document content editable and preserves explicit run emphasis and colors.
"""

from __future__ import annotations

from copy import deepcopy
import re

from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Mm, Pt, RGBColor
from docx.text.run import Run

from fcv_presentation import normalize_display_text, split_first_sentence


NAVY = RGBColor(0x15, 0x39, 0x56)
TEAL = RGBColor(0x00, 0x7F, 0x86)
MUTED = RGBColor(0x66, 0x70, 0x85)
BLACK = RGBColor(0, 0, 0)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
PALE_BLUE = "EAF2F8"
PALE_TEAL = "E7F3F1"
PALE_GREEN = "EEF7EF"
PALE_ORANGE = "FFF4E5"

_METADATA_PREFIXES = (
    "AI-Generated Output",
    "Generated by ",
    "Prepared for ",
    "Assessment ID:",
    "Project ID:",
    "Document:",
    "Source:",
    "Date:",
)


def _set_font(
    font,
    *,
    size: float | None = None,
    color: RGBColor | None = None,
    bold: bool | None = None,
) -> None:
    font.name = "Arial"
    if size is not None:
        font.size = Pt(size)
    if color is not None:
        font.color.rgb = color
    if bold is not None:
        font.bold = bold


def _set_style_font(
    style,
    *,
    size: float | None = None,
    color: RGBColor | None = None,
    bold: bool | None = None,
) -> None:
    _set_font(style.font, size=size, color=color, bold=bold)
    rpr = style.element.get_or_add_rPr()
    rfonts = rpr.rFonts
    if rfonts is None:
        rfonts = OxmlElement("w:rFonts")
        rpr.insert(0, rfonts)
    for attribute in ("ascii", "hAnsi", "eastAsia", "cs"):
        rfonts.set(qn(f"w:{attribute}"), "Arial")


def _paragraph_runs(paragraph) -> list[Run]:
    return [Run(element, paragraph) for element in paragraph._p.iter(qn("w:r"))]


def _set_shading(element, fill: str) -> None:
    shading = element.find(qn("w:shd"))
    if shading is None:
        shading = OxmlElement("w:shd")
        element.append(shading)
    shading.set(qn("w:val"), "clear")
    shading.set(qn("w:color"), "auto")
    shading.set(qn("w:fill"), fill)


def _set_border(element, side: str, color: str, size: str = "12") -> None:
    borders = element.find(qn("w:pBdr"))
    if borders is None:
        borders = OxmlElement("w:pBdr")
        element.append(borders)
    border = borders.find(qn(f"w:{side}"))
    if border is None:
        border = OxmlElement(f"w:{side}")
        borders.append(border)
    border.set(qn("w:val"), "single")
    border.set(qn("w:sz"), size)
    border.set(qn("w:space"), "0")
    border.set(qn("w:color"), color)


def _set_paragraph_accent(paragraph, fill: str) -> None:
    ppr = paragraph._p.get_or_add_pPr()
    _set_shading(ppr, fill)
    _set_border(ppr, "left", "007F86", size="12")


def _set_cell_shading(cell, fill: str) -> None:
    tcpr = cell._tc.get_or_add_tcPr()
    _set_shading(tcpr, fill)


def _add_page_field(paragraph) -> None:
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    instruction = OxmlElement("w:instrText")
    instruction.set(qn("xml:space"), "preserve")
    instruction.text = " PAGE "
    separate = OxmlElement("w:fldChar")
    separate.set(qn("w:fldCharType"), "separate")
    result = OxmlElement("w:t")
    result.text = "1"
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run = paragraph.add_run()
    _set_font(run.font, size=8.5, color=MUTED)
    run._r.append(begin)
    run._r.append(instruction)
    run._r.append(separate)
    run._r.append(result)
    run._r.append(end)


def _should_bold_first_sentence(paragraph, text: str, runs: list[Run]) -> bool:
    style_name = paragraph.style.name if paragraph.style is not None else ""
    if not text or style_name in {"Title", "Subtitle", "Caption", "Header", "Footer"}:
        return False
    if style_name.startswith("Heading "):
        return False
    if text.startswith(_METADATA_PREFIXES):
        return False
    visible_runs = [run for run in runs if run.text and run.text.strip()]
    return not visible_runs or not all(run.bold is True for run in visible_runs)


def _split_run_for_bold(run: Run, prefix_length: int) -> None:
    text = run.text or ""
    if prefix_length <= 0:
        return
    if prefix_length >= len(text):
        run.bold = True
        return
    suffix_r = deepcopy(run._r)
    run.text = text[:prefix_length]
    suffix = Run(suffix_r, run._parent)
    suffix.text = text[prefix_length:]
    run._r.addnext(suffix._r)
    run.bold = True


def _bold_first_sentence(paragraph, text: str) -> None:
    first, _ = split_first_sentence(text)
    if not first:
        return
    boundary = len(first)
    offset = 0
    for run in _paragraph_runs(paragraph):
        run_text = run.text or ""
        next_offset = offset + len(run_text)
        if offset < boundary:
            if next_offset <= boundary:
                run.bold = True
            else:
                _split_run_for_bold(run, boundary - offset)
                break
        offset = next_offset
        if offset >= boundary:
            break


def _style_body_paragraph(paragraph) -> None:
    paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
    style_name = paragraph.style.name if paragraph.style is not None else ""
    if style_name == "Title":
        heading_color = BLACK
    elif style_name.startswith("Heading "):
        heading_color = NAVY
    else:
        heading_color = None

    runs = _paragraph_runs(paragraph)
    for run in runs:
        run.text = normalize_display_text(run.text or "")
        _set_font(run.font, color=heading_color)
        if (
            run.bold
            and run.text.rstrip().endswith(":")
            and run.text.strip().startswith(("Why it matters:", "Suggested action:"))
        ):
            run.font.color.rgb = TEAL

    text = paragraph.text.strip()
    if style_name == "Title":
        for border in paragraph._p.xpath("./w:pPr/w:pBdr"):
            border.getparent().remove(border)
    if style_name.startswith("Heading ") and re.match(
        r"^(?:Priority\s+\d+|\d+\.)", text, re.IGNORECASE
    ):
        _set_paragraph_accent(paragraph, PALE_BLUE)
    elif text.lower() in {"strengths", "what the project does well"}:
        _set_paragraph_accent(paragraph, PALE_GREEN)
    elif text.lower() == "potential gaps" or re.match(r"^gap(?:\s+\d+)?:", text, re.IGNORECASE):
        _set_paragraph_accent(paragraph, PALE_ORANGE)
    elif text.lower().startswith("suggested text:"):
        paragraph.paragraph_format.keep_with_next = True
        _set_paragraph_accent(paragraph, PALE_TEAL)
    elif text.startswith("Why it matters:"):
        _set_paragraph_accent(paragraph, PALE_BLUE)
    elif text.startswith("Suggested action:"):
        _set_paragraph_accent(paragraph, PALE_TEAL)

    if _should_bold_first_sentence(paragraph, text, runs):
        _bold_first_sentence(paragraph, text)


def _style_table(table) -> None:
    if not table.rows:
        return
    header = table.rows[0]
    trpr = header._tr.get_or_add_trPr()
    repeated = trpr.find(qn("w:tblHeader"))
    if repeated is None:
        repeated = OxmlElement("w:tblHeader")
        trpr.append(repeated)
    repeated.set(qn("w:val"), "true")
    for cell in header.cells:
        _set_cell_shading(cell, "153956")
        cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
        for paragraph in cell.paragraphs:
            paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
            for run in _paragraph_runs(paragraph):
                _set_font(run.font, size=9.5, color=WHITE, bold=True)
    for row in table.rows[1:]:
        for cell in row.cells:
            for paragraph in cell.paragraphs:
                paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
                for run in _paragraph_runs(paragraph):
                    run.text = normalize_display_text(run.text or "")
                    _set_font(run.font)


def _style_header(section, label: str, line_height: float) -> None:
    header = section.header.paragraphs[0]
    header.clear()
    header.alignment = WD_ALIGN_PARAGRAPH.LEFT
    header.paragraph_format.space_before = Pt(0)
    header.paragraph_format.space_after = Pt(0)
    header.paragraph_format.line_spacing = Pt(line_height)
    header.paragraph_format.left_indent = Inches(-section.left_margin.inches)
    header.paragraph_format.right_indent = Inches(-section.right_margin.inches)
    header.paragraph_format.first_line_indent = Inches(section.left_margin.inches)
    ppr = header._p.get_or_add_pPr()
    _set_shading(ppr, "153956")
    _set_border(ppr, "bottom", "007F86", size="14")
    run = header.add_run(label)
    _set_font(run.font, size=8.5, color=WHITE, bold=True)


def _style_footer(section, label: str) -> None:
    footer = section.footer.paragraphs[0]
    footer.clear()
    footer.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    footer.paragraph_format.space_before = Pt(0)
    footer.paragraph_format.space_after = Pt(0)
    run = footer.add_run(f"{label} | Page ")
    _set_font(run.font, size=8.5, color=MUTED)
    _add_page_field(footer)


def style_fcv_word_document(document, *, variant: str = "brief"):
    """Apply editable FCV Word styling to a completed document."""
    if variant not in {"brief", "detail"}:
        raise ValueError("Word style variant must be 'brief' or 'detail'.")

    sizes = (
        (17, 12.5, 11.5, 11)
        if variant == "brief"
        else (20, 15, 12.5, 11.5)
    )
    title_size, heading1_size, heading2_size, heading3_size = sizes
    body_size = 11 if variant == "brief" else 11.5
    for name in (
        "Normal",
        "Title",
        "Heading 1",
        "Heading 2",
        "Heading 3",
        "Heading 4",
        "List Bullet",
    ):
        if name not in document.styles:
            continue
        style = document.styles[name]
        style.paragraph_format.space_after = Pt(5 if variant == "brief" else 4)
        if variant == "brief" and name.startswith("Heading "):
            style.paragraph_format.space_before = Pt(8)
        if name == "Normal":
            _set_style_font(style, size=body_size, color=BLACK)
            style.paragraph_format.widow_control = True
            if variant == "brief":
                style.paragraph_format.line_spacing = 1.15
        elif name == "Title":
            _set_style_font(style, size=title_size, color=BLACK, bold=True)
            for border in style.element.xpath("./w:pPr/w:pBdr"):
                border.getparent().remove(border)
        elif name == "Heading 1":
            _set_style_font(style, size=heading1_size, color=NAVY, bold=True)
        elif name == "Heading 2":
            _set_style_font(style, size=heading2_size, color=NAVY, bold=True)
        elif name == "Heading 3":
            _set_style_font(style, size=heading3_size, color=NAVY, bold=True)
        elif name == "Heading 4":
            _set_style_font(style, size=heading3_size - 1, color=NAVY, bold=True)
        else:
            _set_style_font(style, size=body_size, color=BLACK)
        style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.LEFT
        if name in {"Title", "Heading 1", "Heading 2", "Heading 3", "Heading 4"}:
            style.paragraph_format.keep_with_next = True

    for paragraph in document.paragraphs:
        _style_body_paragraph(paragraph)

    for table in document.tables:
        _style_table(table)

    document.settings.odd_and_even_pages_header_footer = False
    header_line_height = 28 if variant == "brief" else 42.5
    for section in document.sections:
        section.different_first_page_header_footer = False
        section.header_distance = Mm(0)
        section.footer_distance = Mm(8)
        header_label = (
            "FCV MANAGEMENT BRIEF | ADVISORY OUTPUT"
            if variant == "brief"
            else "FCV ASSESSMENT | ADVISORY OUTPUT"
        )
        footer_label = (
            "FCV management brief" if variant == "brief" else "FCV assessment"
        )
        _style_header(section, header_label, header_line_height)
        _style_footer(section, footer_label)
    return document
