"""Public integration surface for the sector-lens registry foundation."""

from .budgets import MAX_ACTIVE_LENSES, PLATFORM_STAGE_BUDGETS
from .composer import build_stage_slice, estimate_tokens, resolve_active_lenses
from .models import (
    ActiveLensSelection,
    DetectionConfig,
    LensActivationMode,
    LensDiagnostic,
    LensCompatibility,
    LensLoadError,
    LensLoadStatus,
    LensMetadata,
    LensQuestion,
    LensReadoutSection,
    LensRegistry,
    LensSelectionWarning,
    LensSource,
    LensStatus,
    SectorLens,
    StageBudgets,
    StageSlice,
)
from .registry import load_registry
from .pipeline import (
    LENS_DIAGNOSTIC_END,
    LENS_DIAGNOSTIC_START,
    LENS_EVIDENCE_END,
    LENS_EVIDENCE_START,
    detect_lens_suggestions,
    extract_lens_diagnostic,
    extract_lens_evidence,
    lens_catalogue,
    merge_lens_findings,
    normalize_lens_diagnostic,
    strip_lens_blocks,
)

__all__ = [
    "ActiveLensSelection",
    "DetectionConfig",
    "LensActivationMode",
    "LensDiagnostic",
    "LensCompatibility",
    "LensLoadError",
    "LensLoadStatus",
    "LensMetadata",
    "LensQuestion",
    "LensReadoutSection",
    "LensRegistry",
    "LensSelectionWarning",
    "LensSource",
    "LensStatus",
    "MAX_ACTIVE_LENSES",
    "PLATFORM_STAGE_BUDGETS",
    "SectorLens",
    "StageBudgets",
    "StageSlice",
    "build_stage_slice",
    "estimate_tokens",
    "load_registry",
    "LENS_DIAGNOSTIC_END",
    "LENS_DIAGNOSTIC_START",
    "LENS_EVIDENCE_END",
    "LENS_EVIDENCE_START",
    "detect_lens_suggestions",
    "extract_lens_diagnostic",
    "extract_lens_evidence",
    "lens_catalogue",
    "merge_lens_findings",
    "normalize_lens_diagnostic",
    "resolve_active_lenses",
    "strip_lens_blocks",
]
